spring:
  datasource:
    url : jdbc:mysql://localhost:3306/fabricVendor?useSSL=False
    username : // Pls use user name of your database.
    password : // Pls use password of your database.

#JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true